# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 18:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 7, 18, 40, 51, 903988, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
